CREATE TABLE IF NOT EXISTS partners (
    id INT AUTO_INCREMENT PRIMARY KEY,
    account_id INT NULL,
    category_id INT NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    description TEXT,
    short_description VARCHAR(500),
    contact_name VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    website VARCHAR(255),
    address VARCHAR(255),
    city VARCHAR(100),
    postal_code VARCHAR(20),
    price_from INT,
    price_description VARCHAR(255),
    logo_url VARCHAR(500),
    cover_image_url VARCHAR(500),
    status ENUM('pending', 'approved', 'rejected', 'suspended') DEFAULT 'pending',
    is_featured TINYINT(1) DEFAULT 0,
    rejection_reason TEXT,
    service_areas TEXT,
    nationwide TINYINT(1) DEFAULT 0,
    view_count INT DEFAULT 0,
    inquiry_count INT DEFAULT 0,
    approved_at TIMESTAMP NULL,
    approved_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_partner_status (status),
    INDEX idx_partner_category (category_id),
    INDEX idx_partner_featured (is_featured)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
